### ISSUE TITLE
Higsby mission 3 issue

### ISSUE THREAD

**Issue by ultimatt1995** [XKirby/MMBN3-Randomizer#4]
I've randomized 5 plus times and each time the 3rd mission Higsby gives me after Beastman is glitched. The red navi says I don't have the chip and I can't progress any further. I just downloaded the newest version today hoping that it was a glitch from when I first downloaded it a month ago. I'm running the game on an Ez flash cart on DS lite hardware, am I doing something wrong or is there just a bug?

Seed: Sun Feb  7 09:12:50 2021
Hash: 49-c-64 21-c-64 5f-5f-21 58-64-48 61-53-4e

Chip Damage Multiplier: 2.0
Chip Damage Variance: 0.5
Enemy HP Multiplier: 2.0
Enemy HP Variance: 0.5
Chip Codes Mode: 2
Randomized Chip Names?: False
Randomized Enemy Names?: False
Randomized NaviCust Shapes?: False
Random Battlefield Mode: 1
Random Element Mode: 3
Randomize Navis?: False
Folder Lock Mode: 0
OMEGA Mode: 0
RegMem Max Range: 50
HELL Mode: 0

Allow Folders?: True
Allow Blue Mystery Data?: True
Allow Green Mystery Data?: True
Allow Shops?: True
Allow Battle Chips?: True
Allow Viruses?: True
Allow NPC Trades?: False

Allow Easy Tutorial?: True
Randomize Battle Objects?: False
Free BattleChips in Shops?: True
Fill Shops?: True
Ignore HP/Damage Limiters?: False

**Comment by XKirby** [comment]
Check the Shop in Cyber ACDC 2 for Ratton1 C. If it's not there, you'll have to start over, as that trade was patched out of the shop due to recent updates that actually fixed this. For future reference, some chips are still in Cyber ACDC 2 for story progression, anything that costs 100z is used for the story.

Also, try your best not to load old saves with new rando runs. Things might not end up as you expect.

EDIT: I noticed you have "Allow NPC Trades" set to False. That may be the issue, since "Blue Mystery Data" is set to True. There a still technically a few headaches with this I need to fix, but try making both of these the same value on a new rando run and let me know what happens.

**Comment by ultimatt1995** [comment]
I do have the chip its asking for(Snake A), but the Navi says I don’t have it(it’s not equipped or anything like that) and the version I used was 3.9.3 which I think is the newest version. I downloaded it yesterday morning because of the previous issues with it. I bought all of the chips from ACDC 2, but none of them are the needed chip.

Just saw the edit will give it a try tomorrow.

**Comment by ultimatt1995** [comment]
I turned both of them off/set to false and that solved the problem, the Navi took the chip this time. Thanks for the information, I’ll keep playing and let you know if I encounter anything else problematic. Thanks for the randomizer by the way.
